# MLflow with PostgreSQL + S3-compatible artifact store (MinIO) support
FROM ghcr.io/mlflow/mlflow:v3.16.0@sha256:470607da2a70fa38724d3d7db0a54a78b50fac708f7291bfebe1935fa95259ae
RUN pip install --no-cache-dir psycopg2-binary boto3
