FROM quay.io/jupyterhub/jupyterhub:4@sha256:11ad46166793bda75267f4aedef371c8003621e442cb32c1beb143876c17b3bf

RUN pip install --no-cache-dir \
    "dockerspawner>=13.0,<14" \
    "jupyterhub-nativeauthenticator>=1.2,<2"

COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
