FROM quay.io/jupyter/scipy-notebook:python-3.13@sha256:ec7343ba248a7473c42322e86e7157bef9ebc9253c40a88e573b3fcf607a9a8a

RUN pip install --no-cache-dir \
    mlflow==3.11.1 \
    boto3 \
    "prefect>=3.0.0,<4.0" \
    "ray[client]==2.55.0" \
    xgboost \
    plotly \
    seaborn \
    ipywidgets
