"""Static extraction of a tagged Jupyter notebook into a pipeline-DSL file (ADR 0160, Phase 1).

A data scientist explores in a workbench notebook (ADR 0090); the reviewable, CI-runnable artifact
is a ``@pipeline`` file (ADR 0080). This module closes that gap with the smallest tool that can:
**cell tagging plus static extraction**.

What it does *not* do is as important as what it does:

* **It never executes the notebook.** Tagged cells are parsed with :mod:`ast` and read as literal
  data — no import, no call, no ``exec``. Reading a notebook here carries the same risk as reading
  a YAML file, so an exploratory cell that would hit the network, train for an hour or claim a GPU
  is inert to the extractor.
* **It invents no vocabulary.** The four step tags are exactly the lowerable keys of
  :data:`examlops.pipeline_dsl.ir.STEP_KINDS`, derived from it rather than retyped, so the tag
  vocabulary cannot drift from the IR.
* **It validates nothing itself.** The emitted file is handed straight back to
  :func:`examlops.pipeline_dsl.loader.load_pipeline_file` + :meth:`PipelineDef.compile`, the exact
  in-process call ``exa pipeline compile`` makes. What makes a pipeline valid stays in one place.
* **It is one-directional.** Export reads the notebook and writes the file. Editing the generated
  file never flows back, and re-running export overwrites rather than merging.
* **It never drops a cell silently.** Every code cell that is neither correctly tagged nor tagged
  ``skip-export`` is reported to the caller in :attr:`Extraction.dropped`.
"""

from __future__ import annotations

import ast
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .ir import STEP_KINDS
from .loader import load_pipeline_file

#: Declares named literal values later tagged cells reference by bare name. Never an IR node.
PARAM_TAG = "param"
#: "I meant to leave this out" — dropped like an untagged cell, but without a warning.
SKIP_TAG = "skip-export"

#: The extractable step tags, *derived* from the IR's own step kinds rather than retyped: exactly
#: the lowerable ones, in the IR's declaration order (which is also their dependency order).
#: ``hpo``/``custom_python`` are known to the IR but have no lowering (ADR 0080), so extracting
#: them would only move the eventual refusal from compile time to run time.
STEP_TAGS: tuple[str, ...] = tuple(k for k, spec in STEP_KINDS.items() if spec.lowerable)

#: Every tag the extractor recognises. An unrecognised tag makes a cell *untagged*, never an error.
KNOWN_TAGS: frozenset[str] = frozenset({PARAM_TAG, SKIP_TAG, *STEP_TAGS})

#: Step kinds a notebook may declare at most once. Enforced here so the error names the *cell*
#: rather than arriving later as ``lowering._one``'s opaque "the IR has 2" message.
_SINGLETON_TAGS: frozenset[str] = frozenset({"train", "evaluate", "promote"})

#: The argument each helper takes positionally, and whether the emitter can build the call without
#: it. ``train`` takes ``*datasets``, so an empty one still emits — and the IR then reports the
#: unconnected input, which is the single source of truth for completeness (spec §4.4).
_POSITIONAL: dict[str, str] = {
    "dataset": "name",
    "train": "datasets",
    "evaluate": "model",
    "promote": "metrics",
}
_POSITIONAL_REQUIRED: frozenset[str] = frozenset({"dataset", "evaluate", "promote"})

#: Names the generated file imports; a step variable may not shadow one (``train = train(...)``
#: inside a function body is an ``UnboundLocalError``, not a pipeline).
_RESERVED: frozenset[str] = frozenset({"pipeline", *STEP_TAGS})

_ALLOWED_CONSTANTS = (str, int, float, bool, type(None))
_WIDTH = 96
_PREVIEW = 60
_HEADER = (
    '"""Generated by `exa workbench export-pipeline` from {origin}. Edits here do not flow\n'
    "back into the notebook — re-run export-pipeline to regenerate from a changed notebook "
    'instead."""'
)


class NotebookExportError(ValueError):
    """A notebook the static extractor refuses. The message names the offending cell."""


@dataclass(frozen=True)
class DroppedCell:
    """A code cell excluded from the export, reported so the omission is never discovered later."""

    index: int
    preview: str

    def as_dict(self) -> dict[str, Any]:
        return {"index": self.index, "preview": self.preview}


@dataclass(frozen=True)
class StepSpec:
    """One tagged step cell: the variable it binds, its step kind, and its literal keywords."""

    index: int
    var: str
    kind: str
    kwargs: dict[str, Any]


@dataclass
class Extraction:
    """The result of reading a notebook: the source to write, plus everything left behind."""

    name: str
    source: str
    steps: list[StepSpec] = field(default_factory=list)
    dropped: list[DroppedCell] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    params: dict[str, Any] = field(default_factory=dict)


# ── reading the notebook ──────────────────────────────────────────────────────────────────


def read_notebook(path: str | Path) -> dict[str, Any]:
    """Load an ``.ipynb`` as plain JSON (nbformat is a documented JSON schema; no dependency)."""
    p = Path(path)
    if not p.is_file():
        raise NotebookExportError(f"notebook not found: {p}")
    try:
        doc = json.loads(p.read_text(encoding="utf-8"))
    except ValueError as exc:
        raise NotebookExportError(f"{p.name}: not readable as JSON: {exc}") from exc
    if not isinstance(doc, dict) or not isinstance(doc.get("cells"), list):
        raise NotebookExportError(f"{p.name}: not an nbformat notebook (no 'cells' array)")
    return doc


def _source_of(cell: dict[str, Any]) -> str:
    source = cell.get("source", "")
    if isinstance(source, list):
        return "".join(str(line) for line in source)
    return str(source or "")


def _tags_of(cell: dict[str, Any], index: int, warnings: list[str]) -> list[str]:
    meta = cell.get("metadata")
    tags = meta.get("tags") if isinstance(meta, dict) else None
    if tags is None:
        return []
    if not isinstance(tags, list) or not all(isinstance(t, str) for t in tags):
        warnings.append(f"cell {index}: metadata.tags is not a list of strings — read as untagged")
        return []
    return [str(t) for t in tags]


def _edit_distance_1(a: str, b: str) -> bool:
    """True when ``a`` is one insertion, deletion or substitution away from ``b``."""
    if a == b or abs(len(a) - len(b)) > 1:
        return False
    if len(a) > len(b):
        a, b = b, a
    i = j = 0
    edited = False
    while i < len(a) and j < len(b):
        if a[i] == b[j]:
            i, j = i + 1, j + 1
            continue
        if edited:
            return False
        edited = True
        j += 1
        if len(a) == len(b):
            i += 1
    return True


def _typo_warnings(index: int, tags: list[str]) -> list[str]:
    """An unrecognised tag is otherwise indistinguishable from "no tag" — say it looks like one."""
    out: list[str] = []
    for tag in tags:
        if tag in KNOWN_TAGS:
            continue
        near = sorted(k for k in KNOWN_TAGS if _edit_distance_1(tag, k))
        if near:
            out.append(
                f"cell {index}: tag {tag!r} is not recognised — did you mean "
                f"{' or '.join(repr(n) for n in near)}? The cell was dropped as untagged."
            )
    return out


def _preview(source: str) -> str:
    text = " / ".join(line.strip() for line in source.splitlines() if line.strip())
    return text if len(text) <= _PREVIEW else text[: _PREVIEW - 1].rstrip() + "…"


# ── parsing tagged cells (never executing them) ───────────────────────────────────────────


def _parse(index: int, tag: str, source: str) -> ast.Module:
    try:
        return ast.parse(source)
    except SyntaxError as exc:
        raise NotebookExportError(f"cell {index} ({tag}): is not valid Python: {exc}") from exc


def _literal(node: ast.AST, params: dict[str, Any], where: str, *, names: bool) -> Any:
    """Read one restricted literal out of the AST. Resolves bare names when ``names`` is set."""
    if isinstance(node, ast.Constant):
        if isinstance(node.value, _ALLOWED_CONSTANTS):
            return node.value
        raise NotebookExportError(f"{where}: constant {node.value!r} is not extractable")
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
        inner = _literal(node.operand, params, where, names=names)
        if isinstance(inner, bool) or not isinstance(inner, (int, float)):
            raise NotebookExportError(f"{where}: unary '+'/'-' only applies to a number")
        return -inner if isinstance(node.op, ast.USub) else inner
    if isinstance(node, (ast.List, ast.Tuple)):
        items = [_literal(e, params, where, names=names) for e in node.elts]
        return items if isinstance(node, ast.List) else tuple(items)
    if isinstance(node, ast.Dict):
        out: dict[str, Any] = {}
        for key_node, value_node in zip(node.keys, node.values):
            if key_node is None:
                raise NotebookExportError(f"{where}: dict unpacking ('**') is not extractable")
            key = _literal(key_node, params, where, names=names)
            if not isinstance(key, str):
                raise NotebookExportError(f"{where}: dict keys must be strings, got {key!r}")
            out[key] = _literal(value_node, params, where, names=names)
        return out
    if isinstance(node, ast.Name):
        if not names:
            raise NotebookExportError(
                f"{where}: a 'param' cell assigns literals only, not the name {node.id!r}"
            )
        if node.id not in params:
            raise NotebookExportError(
                f"{where}: {node.id!r} is not declared by an earlier 'param' cell"
            )
        return params[node.id]
    raise NotebookExportError(
        f"{where}: {type(node).__name__} is not extractable — a tagged cell carries literal "
        "values only (no calls, comprehensions, f-strings, operators or imports)"
    )


def _single_target(stmt: ast.stmt, where: str) -> tuple[ast.Assign, str]:
    """``NAME = <value>`` and nothing else — the only statement shape a tagged cell may carry."""
    if not isinstance(stmt, ast.Assign) or len(stmt.targets) != 1:
        raise NotebookExportError(
            f"{where}: every statement must be 'NAME = <literal>', got {type(stmt).__name__}"
        )
    target = stmt.targets[0]
    if not isinstance(target, ast.Name):
        raise NotebookExportError(f"{where}: assign to a plain NAME only")
    return stmt, target.id


def _parse_param_cell(index: int, source: str, params: dict[str, Any]) -> None:
    where = f"cell {index} (param)"
    for stmt in _parse(index, PARAM_TAG, source).body:
        assign, name = _single_target(stmt, where)
        if name in params:
            raise NotebookExportError(
                f"{where}: {name!r} is already declared by an earlier 'param' cell"
            )
        params[name] = _literal(assign.value, params, f"{where} {name}", names=False)


def _parse_step_cell(index: int, tag: str, source: str, params: dict[str, Any]) -> StepSpec:
    body = _parse(index, tag, source).body
    where = f"cell {index} ({tag})"
    if len(body) != 1:
        raise NotebookExportError(
            f"{where}: must be exactly one 'VAR = {{...}}' assignment, got {len(body)} statement(s)"
        )
    assign, var = _single_target(body[0], where)
    if var in _RESERVED:
        raise NotebookExportError(
            f"{where}: {var!r} is the name of the DSL helper the generated file imports — "
            "rename the cell's variable"
        )
    if not isinstance(assign.value, ast.Dict):
        raise NotebookExportError(f"{where}: the assigned value must be a dict literal")
    kwargs: dict[str, Any] = _literal(assign.value, params, where, names=True)
    return StepSpec(index=index, var=var, kind=tag, kwargs=dict(kwargs))


# ── wiring ────────────────────────────────────────────────────────────────────────────────


def _resolve_input(
    spec: StepSpec, kwargs: dict[str, Any], key: str, by_var: dict[str, StepSpec]
) -> list[str]:
    """Pop ``key`` off ``kwargs`` and return the step variable names it wires this step to.

    These extractor-only keys never reach the DSL call as params: they become its positional
    argument, exactly as ``dsl.train``/``evaluate``/``promote`` separate inputs from ``**params``.
    """
    where = f"cell {spec.index} ({spec.kind})"
    raw = kwargs.pop(key, None)
    if raw is None:
        if spec.kind in _POSITIONAL_REQUIRED:
            raise NotebookExportError(
                f"{where}: needs {key!r} — the variable name of the step cell it consumes"
            )
        return []
    wanted = raw if isinstance(raw, list) else [raw]
    names: list[str] = []
    for item in wanted:
        if not isinstance(item, str):
            raise NotebookExportError(f"{where}: {key!r} names step variables as strings")
        if item not in by_var:
            raise NotebookExportError(
                f"{where}: {key!r} names {item!r}, which is not a tagged step cell's variable "
                f"(known: {', '.join(sorted(by_var)) or 'none'})"
            )
        names.append(item)
    if key != "datasets" and len(names) != 1:
        raise NotebookExportError(f"{where}: {key!r} names exactly one step variable")
    return names


# ── emitting the pipeline file ────────────────────────────────────────────────────────────


def _inline(value: Any) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, dict):
        return "{" + ", ".join(f"{_inline(k)}: {_inline(v)}" for k, v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_inline(v) for v in value) + "]"
    if isinstance(value, tuple):
        body = ", ".join(_inline(v) for v in value)
        return f"({body},)" if len(value) == 1 else f"({body})"
    raise NotebookExportError(f"value {value!r} cannot be written as a Python literal")


def _render(value: Any, indent: int) -> str:
    """One literal as source: on one line when it fits, one item per line when it does not."""
    flat = _inline(value)
    if indent + len(flat) <= _WIDTH or not isinstance(value, (dict, list, tuple)):
        return flat
    pad, inner = " " * indent, " " * (indent + 4)
    if isinstance(value, dict):
        rows = [f"{inner}{_inline(k)}: {_render(v, indent + 4)}," for k, v in value.items()]
        return "{\n" + "\n".join(rows) + "\n" + pad + "}"
    open_, close = ("[", "]") if isinstance(value, list) else ("(", ")")
    rows = [f"{inner}{_render(v, indent + 4)}," for v in value]
    return open_ + "\n" + "\n".join(rows) + "\n" + pad + close


def _call(var: str, fn: str, positional: list[str], kwargs: dict[str, Any]) -> str:
    for key in kwargs:
        # A key that is not an identifier would emit a file that fails to *parse*, which arrives
        # as a SyntaxError from the loader rather than a message naming the cell.
        if not key.isidentifier():
            raise NotebookExportError(
                f"{fn} step {var!r}: {key!r} is not a usable keyword — a step cell's dict keys "
                "are the step's parameter names"
            )
    args = [*positional, *(f"{k}={_inline(v)}" for k, v in kwargs.items())]
    one_line = f"    {var} = {fn}({', '.join(args)})"
    if len(one_line) <= _WIDTH:
        return one_line
    parts = [*positional, *(f"{k}={_render(v, 8)}" for k, v in kwargs.items())]
    body = "\n".join(f"        {part}," for part in parts)
    return f"    {var} = {fn}(\n{body}\n    )"


def _function_name(name: str) -> str:
    cleaned = re.sub(r"\W", "_", name) or "notebook"
    if not (cleaned[0].isalpha() or cleaned[0] == "_"):
        cleaned = "p_" + cleaned
    return f"{cleaned}_pipeline" if cleaned in _RESERVED else cleaned


def render_source(name: str, steps: list[StepSpec], *, origin: str) -> str:
    """Emit the ``@pipeline`` file for already-wired steps, in IR dependency order."""
    by_var = {s.var: s for s in steps}
    ordered = [s for tag in STEP_TAGS for s in steps if s.kind == tag]
    lines: list[str] = []
    used: set[str] = set()
    for spec in ordered:
        kwargs = dict(spec.kwargs)
        positional: list[str] = []
        key = _POSITIONAL[spec.kind]
        if spec.kind == "dataset":
            if "name" not in kwargs:
                raise NotebookExportError(
                    f"cell {spec.index} (dataset): needs 'name' — it is the dataset's identity "
                    "and the helper's positional argument"
                )
            positional = [_inline(kwargs.pop("name"))]
        else:
            positional = _resolve_input(spec, kwargs, key, by_var)
        used.add(spec.kind)
        lines.append(_call(spec.var, spec.kind, positional, kwargs))
    imports = ", ".join(sorted({"pipeline", *used}))
    body = "\n".join(lines) if lines else "    pass"
    return (
        _HEADER.format(origin=origin)
        + f"\n\nfrom examlops.sdk import {imports}\n\n\n"
        + f'@pipeline(name="{name}")\n'
        + f"def {_function_name(name)}():\n"
        + body
        + "\n"
    )


# ── the extractor ─────────────────────────────────────────────────────────────────────────


def extract_notebook(path: str | Path, *, name: str | None = None) -> Extraction:
    """Read a tagged notebook and return the pipeline source it declares, plus what was dropped.

    Never executes, imports or evaluates anything in the notebook.
    """
    doc = read_notebook(path)
    pipeline_name = name or Path(path).stem
    if not pipeline_name.strip():
        raise NotebookExportError("pipeline name is empty — pass --name")
    params: dict[str, Any] = {}
    steps: list[StepSpec] = []
    dropped: list[DroppedCell] = []
    warnings: list[str] = []
    first_seen: dict[str, int] = {}

    for index, cell in enumerate(doc["cells"]):
        if not isinstance(cell, dict) or cell.get("cell_type") != "code":
            continue
        source = _source_of(cell)
        tags = _tags_of(cell, index, warnings)
        recognised = sorted({t for t in tags if t in KNOWN_TAGS})
        if len(recognised) > 1:
            raise NotebookExportError(
                f"cell {index}: carries several recognised tags ({', '.join(recognised)}); "
                "a cell may carry at most one"
            )
        warnings.extend(_typo_warnings(index, tags))
        if not recognised:
            if source.strip():
                dropped.append(DroppedCell(index, _preview(source)))
            continue
        tag = recognised[0]
        if tag == SKIP_TAG:
            continue
        if tag == PARAM_TAG:
            _parse_param_cell(index, source, params)
            continue
        if tag in _SINGLETON_TAGS and tag in first_seen:
            raise NotebookExportError(
                f"cell {index} ({tag}): a notebook declares exactly one {tag!r} cell; "
                f"cell {first_seen[tag]} already is one"
            )
        first_seen.setdefault(tag, index)
        spec = _parse_step_cell(index, tag, source, params)
        if any(s.var == spec.var for s in steps):
            raise NotebookExportError(
                f"cell {index} ({tag}): variable {spec.var!r} is already bound by an earlier "
                "tagged cell — each step needs its own name"
            )
        steps.append(spec)

    source_text = render_source(pipeline_name, steps, origin=Path(path).name)
    return Extraction(
        name=pipeline_name,
        source=source_text,
        steps=steps,
        dropped=dropped,
        warnings=warnings,
        params=params,
    )


def export_notebook(
    path: str | Path, out: str | Path, *, name: str | None = None
) -> tuple[Extraction, dict[str, Any]]:
    """Extract, write ``out``, then compile it through the ordinary pipeline-DSL path.

    The file is written *before* compiling, so a pipeline the IR rejects is still on disk for the
    author to fix; the :class:`~examlops.pipeline_dsl.ir.IRError` propagates unchanged so the
    caller reports the compiler's own message rather than a re-worded one.
    """
    extraction = extract_notebook(path, name=name)
    target = Path(out)
    if not target.parent.exists():
        raise NotebookExportError(f"output directory does not exist: {target.parent}")
    target.write_text(extraction.source, encoding="utf-8")
    pdef, _ = load_pipeline_file(str(target))
    return extraction, pdef.compile()
