"""Agent versions as registry artifacts (ADR 0146): manifest, registry, aliases, promotion gate."""

from examlops.agent_versions.manifest import (
    ALIASES,
    AUTONOMY_LEVELS,
    SCHEMA_VERSION,
    AgentManifestError,
    canonical_json,
    diff_manifests,
    mcp_tool_manifest,
    normalize,
    tool_manifest_hash,
    version_id_of,
)
from examlops.agent_versions.service import (
    IN_FLIGHT_POLICIES,
    AgentVersion,
    GateRefusal,
    canonical_alias,
    diff,
    evidence_refusals,
    get,
    list_versions,
    model_key,
    register,
    resolve,
    rollback,
    set_alias,
    set_canary,
    verify_signature,
)

__all__ = [
    "ALIASES",
    "AUTONOMY_LEVELS",
    "IN_FLIGHT_POLICIES",
    "SCHEMA_VERSION",
    "AgentManifestError",
    "AgentVersion",
    "GateRefusal",
    "canonical_alias",
    "canonical_json",
    "diff",
    "diff_manifests",
    "evidence_refusals",
    "get",
    "list_versions",
    "mcp_tool_manifest",
    "model_key",
    "normalize",
    "register",
    "resolve",
    "rollback",
    "set_alias",
    "set_canary",
    "tool_manifest_hash",
    "verify_signature",
    "version_id_of",
]
