#!/usr/bin/env python3
"""Render the docs site's roadmap list from docs/assets/explore/data/roadmap.json.

The roadmap page (docs/explore/roadmap.md) shows an interactive, filterable timeline built by
assets/explore/js/xm-roadmap.js from roadmap.json. The same items are also written into the page
as plain Markdown, between two markers, so they are indexed by the site search and readable with
JavaScript off. This script writes that block; roadmap.json stays the single source.

Run:   python3 platform/ci/gen_roadmap_page.py            # rewrite the block
       python3 platform/ci/gen_roadmap_page.py --check    # exit 1 if the page is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs" / "assets" / "explore" / "data" / "roadmap.json"
PAGE = ROOT / "docs" / "explore" / "roadmap.md"
BEGIN = "<!-- roadmap:begin (generated by platform/ci/gen_roadmap_page.py) -->"
END = "<!-- roadmap:end -->"
STATUS = {
    "partial": "partly built",
    "planned": "planned",
    "in design": "in design",
    "deferred": "deferred",
}


def render(data: dict) -> str:
    out = [BEGIN, "", '<div class="xm-roadmap" markdown>', ""]
    out.append("### Shipped")
    out.append("")
    for era in data["shipped"]:
        out.append(f"**{era['name']}** — {era['span']}, {len(era['items'])} milestones")
        out.append("")
        for item in era["items"]:
            out.append(f"- **{item['title']}.** {item['text']}")
        out.append("")
    out.append("### Under construction")
    out.append("")
    for track in data["planned"]:
        out.append(f"**{track['name']}** — {track['text']}")
        out.append("")
        for item in track["items"]:
            out.append(
                f"- **{item['title']}** ({STATUS.get(item['status'], item['status'])}). "
                f"{item['text']}"
            )
        out.append("")
    out += ["</div>", "", END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the page is stale")
    args = ap.parse_args()
    page = PAGE.read_text()
    if BEGIN not in page or END not in page:
        print(f"{PAGE.relative_to(ROOT)} has no roadmap markers")
        return 1
    head, rest = page.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + render(json.loads(DATA.read_text())) + tail
    if args.check:
        if new != page:
            print(
                f"{PAGE.relative_to(ROOT)} is stale — run: python3 {Path(__file__).relative_to(ROOT)}"
            )
            return 1
        print("roadmap page up to date")
        return 0
    PAGE.write_text(new)
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
