"""The docs site's "Every capability" atlas must match the live `exa` command tree.

The atlas (docs/explore/capabilities.md + docs/assets/explore/data/capabilities.json) lists
every `exa` command by lifecycle area. It is generated by platform/ci/gen_capability_atlas.py;
this test runs the generator in --check mode, so adding, renaming or removing a command without
regenerating fails here instead of shipping a site that silently omits it.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "platform" / "ci" / "gen_capability_atlas.py"
DATA = ROOT / "docs" / "assets" / "explore" / "data" / "capabilities.json"


def test_atlas_is_up_to_date() -> None:
    result = subprocess.run(
        [sys.executable, str(GEN), "--check"], capture_output=True, text=True, cwd=ROOT
    )
    assert result.returncode == 0, (
        f"{result.stdout}{result.stderr}\n"
        "Regenerate with: python3 platform/ci/gen_capability_atlas.py"
    )


def test_every_command_links_somewhere() -> None:
    data = json.loads(DATA.read_text())
    unlinked = [c["cmd"] for p in data["panels"] for c in p["commands"] if not c["anchor"]]
    assert not unlinked, f"commands with no section in the CLI command guide: {unlinked}"


def test_no_command_left_outside_a_lifecycle_area() -> None:
    data = json.loads(DATA.read_text())
    other = [p for p in data["panels"] if p["title"] == "Other"]
    assert not other, f"top-level groups missing from _ROOT_PANELS: {other[0]['groups']}"


def test_roadmap_page_matches_its_data() -> None:
    """docs/explore/roadmap.md's static list is rendered from roadmap.json; keep them in step."""
    result = subprocess.run(
        [sys.executable, str(ROOT / "platform" / "ci" / "gen_roadmap_page.py"), "--check"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_roadmap_data_is_public_safe() -> None:
    """The roadmap is published: no private paths, hosts or flagged-sensitive items."""
    text = (ROOT / "docs" / "assets" / "explore" / "data" / "roadmap.json").read_text()
    for token in (".claude", "paper/", "design/adr", '"sensitive"', "lxp", "23.109."):
        assert token not in text, f"roadmap.json contains {token!r}"
