"""The install bundle is what an operator runs on a fresh machine; hold it to that.

`platform/infra/docker-compose/install/` is the single-node deployment shipped with a release. It
must work from the release tarball alone, on a host that has never seen this repository — so it may
not build, may not reach outside its own directory, and may not start with a credential anyone
could guess. The development stack beside it does all three on purpose (it builds from the tree,
bind-mounts the repo, and defaults MinIO to `minioadmin`), which is exactly why a copy-and-trim of
it drifts back into those habits unless something reads the file.

Every test here reads the files directly. Only the last one needs `docker`, and it skips without.
"""

from __future__ import annotations

import base64
import os
import re
import shutil
import stat
import subprocess
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
BUNDLE = REPO / "platform" / "infra" / "docker-compose" / "install"
COMPOSE = BUNDLE / "docker-compose.yml"
TEMPLATE = BUNDLE / "env.template"
INSTALL = BUNDLE / "install.sh"
RELEASE = REPO / ".github" / "workflows" / "release.yml"

APP_IMAGE = re.compile(
    r"^\$\{EXAMLOPS_REGISTRY:-ghcr\.io/mskazemi\}/examlops-(?P<name>[a-z0-9-]+)"
    r":\$\{EXAMLOPS_VERSION(:\?[^}]*)?\}$"
)
PINNED_UPSTREAM = re.compile(r"^[a-z0-9./_-]+:[A-Za-z0-9._-]+@sha256:[0-9a-f]{64}$")
STATE_MOUNT = "${EXAMLOPS_STATE_DIR:-./state}:/state:rw"
DOCKER_SOCKET_RO = "/var/run/docker.sock:/var/run/docker.sock:ro"

# Credentials the stack cannot run safely without. Each must be required (`:?`) wherever compose
# reads it, and generated by `install.sh init`.
SECRETS = (
    "POSTGRES_PASSWORD",
    "MINIO_ROOT_USER",
    "MINIO_ROOT_PASSWORD",
    "MINIO_SERVING_ACCESS_KEY",
    "MINIO_SERVING_SECRET_KEY",
    "CONTROL_PLANE_TOKEN",
    "DASHBOARD_VIEWER_PASSWORD",
    "DASHBOARD_ADMIN_PASSWORD",
    "DASHBOARD_JWT_SECRET",
    "DASHBOARD_SECRET_KEY",
)
# Values that have shipped as defaults in the development stack and must never reach an install.
WEAK_DEFAULTS = ("minioadmin", "changeme", ":-mlops}", ":-admin}", "GRAFANA_ADMIN_PASSWORD")


def _compose() -> dict:
    return yaml.safe_load(COMPOSE.read_text())


def _services() -> dict[str, dict]:
    return _compose()["services"]


def _template_keys() -> dict[str, str]:
    keys = {}
    for line in TEMPLATE.read_text().splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            key, _, value = line.partition("=")
            keys[key.strip()] = value.strip()
    return keys


_VARIABLE = re.compile(r"\$\{([A-Z0-9_]+)(:[?-]|[?-]|)")


def _variables_in(text: str) -> list[tuple[str, str]]:
    """Every `${VAR<op>…}` compose interpolates from the host, as (name, operator).

    `$${…}` is escaped for the container's own shell and is not a host variable.
    """
    return _VARIABLE.findall(re.sub(r"\$\$\{[^}]*\}", "", text))


def _host_variables() -> list[tuple[str, str]]:
    return _variables_in(COMPOSE.read_text())


def _released_images() -> set[str]:
    workflow = yaml.safe_load(RELEASE.read_text())
    return {entry["name"] for entry in workflow["jobs"]["images"]["strategy"]["matrix"]["include"]}


def test_nothing_is_built_and_nothing_is_named_globally():
    for name, svc in _services().items():
        assert "build" not in svc, f"{name}: the bundle pulls released images, it never builds"
        assert "container_name" not in svc, (
            f"{name}: container_name makes two installs on one host collide; the project name "
            "(EXAMLOPS_PROJECT_NAME) already scopes every container"
        )
        assert "env_file" not in svc, (
            f"{name}: env_file hands every credential in .env to this container; pass only the "
            "variables it uses under environment:"
        )


def test_application_images_are_the_released_ones_at_the_bundle_version():
    released = _released_images()
    seen = set()
    for name, svc in _services().items():
        image = svc["image"]
        match = APP_IMAGE.match(image)
        if match:
            assert match["name"] in released, (
                f"{name}: {image} is not built by .github/workflows/release.yml "
                f"(publishes {sorted(released)}), so no release will ever contain it"
            )
            seen.add(match["name"])
        else:
            assert PINNED_UPSTREAM.match(image), (
                f"{name}: upstream image {image!r} must be pinned as tag@sha256:<digest>"
            )
    assert seen, "the bundle references no ExaMLOps image at all"


def test_nothing_is_mounted_from_outside_the_bundle():
    for name, svc in _services().items():
        for volume in svc.get("volumes", []):
            source = volume.split(":", 1)[0]
            if source.startswith(("$", ".", "/")):
                assert volume in (STATE_MOUNT, DOCKER_SOCKET_RO), (
                    f"{name}: bind mount {volume!r}; the bundle may mount only its state dir and "
                    "the docker socket read-only — never the source tree"
                )
            assert ".." not in volume, f"{name}: {volume!r} reaches outside the bundle"
        # The raw socket is root on the host; only the scoped proxy may hold it.
        if DOCKER_SOCKET_RO in svc.get("volumes", []):
            assert name == "docker-socket-proxy", f"{name} mounts the docker socket"


def test_every_service_on_the_data_root_resolves_the_same_pack():
    for name, svc in _services().items():
        if STATE_MOUNT not in svc.get("volumes", []):
            continue
        env = svc.get("environment", {})
        assert env.get("EXAMLOPS_DATA_DIR") == "/state", name
        assert env.get("EXAMLOPS_USECASE_DIR") == "/state/usecase", (
            f"{name}: without an explicit pack dir, an image with a baked pack would serve it "
            "while the dashboard shows none"
        )
        assert env.get("PLATFORM_DB") == "/state/platform.db", name


def test_the_data_root_is_initialised_before_anything_uses_it():
    services = _services()
    assert "instance init" in " ".join(services["instance-init"]["entrypoint"])
    for name, svc in services.items():
        if name == "instance-init" or STATE_MOUNT not in svc.get("volumes", []):
            continue
        if svc.get("profiles"):
            continue
        deps = svc.get("depends_on", {})
        chain = set(deps)
        for dep in deps:
            chain |= set(services[dep].get("depends_on", {}))
        assert "instance-init" in chain, f"{name} can start before the data root exists"


def test_the_data_root_is_writable_by_every_service():
    """The agent image runs as uid 10001 while the data root is created by root.

    Without the hand-over, `/state/platform.db` is root-owned 0644 and the agent's audit and memory
    writes fail with "attempt to write a readonly database" — every service stays healthy, so
    only a write shows it.
    """
    services = _services()
    init = services["instance-init"]
    script = " ".join(init["entrypoint"])
    assert init.get("user") == "0:0", "only root can hand the data root over"
    assert 'chown -R "$${EXAMLOPS_STATE_UID}:$${EXAMLOPS_STATE_GID}" /state' in script
    assert "chmod -R g+rwX /state" in script and "chmod g+s" in script
    assert services["agent"].get("group_add") == [
        "${EXAMLOPS_STATE_GID:?set EXAMLOPS_STATE_GID in .env (./install.sh init records it)}"
    ]


def test_agent_memory_is_instance_data_the_backup_can_see():
    """The agent (uid 10001) cannot create files in a fresh root-owned named volume.

    Its memory stores therefore live in the group-writable data root — and the backup sidecar
    must read them from the same paths, or a bundle silently omits them.
    """
    services = _services()
    stores = ("AGENT_DB", "AGENT_MEMORY_DB", "AGENT_MEMORY_REVIEW_DB")
    agent_env = services["agent"]["environment"]
    backup_env = services["backup"]["environment"]
    for var in stores:
        assert agent_env[var].startswith("/state/agent/"), f"agent {var}={agent_env[var]}"
        assert backup_env[var] == agent_env[var], f"backup reads {var} from somewhere else"
    assert "mkdir -p /state/agent" in " ".join(services["instance-init"]["entrypoint"])


def test_ports_bind_where_the_operator_says():
    for name, svc in _services().items():
        for port in svc.get("ports", []):
            assert port.startswith(("${EXAMLOPS_BIND:-127.0.0.1}:", "127.0.0.1:")), (
                f"{name}: {port!r} publishes on every interface regardless of EXAMLOPS_BIND"
            )


def test_every_credential_is_required_and_generated():
    """Required (`:?`) in every core service; in a profile-gated one, read with no default.

    A profile-gated service may not use `:?` (compose interpolates before filtering by profile,
    so it would abort every command — test_compose_is_operable), but it must not fall back to a
    default either: the core services already refuse to start without the value.
    """
    template = _template_keys()
    core_ops: dict[str, set[str]] = {}
    gated_ops: dict[str, set[str]] = {}
    for svc in _services().values():
        ops = gated_ops if svc.get("profiles") else core_ops
        for name, op in _variables_in(yaml.safe_dump(svc, width=10_000)):
            ops.setdefault(name, set()).add(op)
    for secret in SECRETS:
        assert secret in core_ops, f"{secret} is never read by a core service"
        assert core_ops[secret] == {":?"}, (
            f"{secret} must be required (${{{secret}:?…}}) in every core service; "
            f"found {sorted(core_ops[secret])}"
        )
        assert gated_ops.get(secret, {""}) == {""}, (
            f"{secret} has a default in a profile-gated service: {sorted(gated_ops[secret])}"
        )
        assert template.get(secret, "").startswith("__GENERATE"), (
            f"env.template must let install.sh generate {secret}"
        )


def test_no_weak_default_survives():
    text = COMPOSE.read_text() + TEMPLATE.read_text()
    for weak in WEAK_DEFAULTS:
        assert weak not in text, f"{weak!r} appears in the install bundle"


def test_template_covers_every_required_variable_and_nothing_dead():
    template = _template_keys()
    used = {name for name, _ in _host_variables()}
    for name, op in _host_variables():
        if op in (":?", "?", ""):
            assert name in template, f"compose requires {name}, env.template does not set it"
    install = INSTALL.read_text()
    for key in template:
        assert key in used or key in install, f"env.template sets {key}, which nothing reads"


def _run_init(tmp_path: Path, *args: str) -> subprocess.CompletedProcess[str]:
    for f in (COMPOSE, TEMPLATE, INSTALL):
        shutil.copy2(f, tmp_path / f.name)
    return subprocess.run(
        ["sh", str(tmp_path / "install.sh"), "init", *args],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin"},
    )


def test_init_generates_every_secret_once_and_keeps_them_private(tmp_path):
    result = _run_init(tmp_path, "--version", "1.2.3")
    assert result.returncode == 0, result.stderr
    env_file = tmp_path / ".env"
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600
    assert (tmp_path / "state").is_dir()

    values = {}
    for line in env_file.read_text().splitlines():
        if line and not line.startswith("#"):
            key, _, value = line.partition("=")
            values[key] = value
    assert values["EXAMLOPS_VERSION"] == "1.2.3"
    assert values["EXAMLOPS_STATE_UID"] == str(os.getuid())
    assert values["EXAMLOPS_STATE_GID"] == str(os.getgid())
    assert not [k for k, v in values.items() if "__" in v], "a placeholder survived init"
    generated = [values[s] for s in SECRETS]
    assert len(set(generated)) == len(generated), "two credentials received the same value"
    assert all(len(v) >= 16 for v in generated)
    assert len(base64.urlsafe_b64decode(values["DASHBOARD_SECRET_KEY"])) == 32, "not a Fernet key"


def test_init_never_clobbers_an_existing_env(tmp_path):
    assert _run_init(tmp_path, "--version", "1.2.3").returncode == 0
    before = (tmp_path / ".env").read_text()
    again = _run_init(tmp_path, "--version", "1.2.3")
    assert again.returncode != 0 and "already exists" in again.stderr
    assert (tmp_path / ".env").read_text() == before


def test_init_refuses_without_a_version(tmp_path):
    result = _run_init(tmp_path)
    assert result.returncode != 0 and "no version" in result.stderr
    assert not (tmp_path / ".env").exists()


@pytest.mark.skipif(shutil.which("docker") is None, reason="docker is not installed")
def test_compose_accepts_a_generated_env_and_rejects_a_missing_secret(tmp_path):
    assert _run_init(tmp_path, "--version", "1.2.3").returncode == 0
    ok = subprocess.run(
        ["docker", "compose", "config", "--quiet"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    if "is not a docker command" in ok.stderr:
        pytest.skip("docker compose v2 is not installed")
    assert ok.returncode == 0, ok.stderr

    env_file = tmp_path / ".env"
    env_file.write_text(
        re.sub(r"(?m)^POSTGRES_PASSWORD=.*$", "POSTGRES_PASSWORD=", env_file.read_text())
    )
    bad = subprocess.run(
        ["docker", "compose", "config", "--quiet"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert bad.returncode != 0 and "POSTGRES_PASSWORD" in bad.stderr
