"""The install bundle is what an operator runs on a fresh machine; hold it to that.

`platform/infra/docker-compose/install/` is the single-node deployment shipped with a release. It
must work from the release tarball alone, on a host that has never seen this repository — so it may
not build, may not reach outside its own directory, and may not start with a credential anyone
could guess. The development stack beside it does all three on purpose (it builds from the tree,
bind-mounts the repo, and defaults MinIO to `minioadmin`), which is exactly why a copy-and-trim of
it drifts back into those habits unless something reads the file.

Every test here reads the files directly. Only the last one needs `docker`, and it skips without.
"""

from __future__ import annotations

import base64
import os
import re
import shutil
import stat
import subprocess
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parents[2]
BUNDLE = REPO / "platform" / "infra" / "docker-compose" / "install"
COMPOSE = BUNDLE / "docker-compose.yml"
TEMPLATE = BUNDLE / "env.template"
INSTALL = BUNDLE / "install.sh"
RELEASE = REPO / ".github" / "workflows" / "release.yml"

APP_IMAGE = re.compile(
    r"^\$\{EXAMLOPS_REGISTRY:-ghcr\.io/mskazemi\}/examlops-(?P<name>[a-z0-9-]+)"
    r":\$\{EXAMLOPS_VERSION(:\?[^}]*)?\}$"
)
PINNED_UPSTREAM = re.compile(r"^[a-z0-9./_-]+:[A-Za-z0-9._-]+@sha256:[0-9a-f]{64}$")
STATE_MOUNT = "${EXAMLOPS_STATE_DIR:-./state}:/state:rw"
DOCKER_SOCKET_RO = "/var/run/docker.sock:/var/run/docker.sock:ro"
_SAFE_BIND = re.compile(
    r"^(\$\{EXAMLOPS_STATE_DIR:-\./state\}/[a-z0-9-]+|\./monitoring/[\w./-]+"
    r"|\./secrets/alertmanager):/[\w./-]+:ro$"
)
MONITORING = BUNDLE / "monitoring"
SOCKET_PROXIES = ("docker-socket-proxy", "logs-proxy")
# The two monitoring configs the bundle owns (the rest are symlinks to tracked dev files).
BUNDLE_OWN_MONITORING = {
    "platform/infra/docker-compose/install/monitoring/prometheus.yml",
    "platform/infra/docker-compose/install/monitoring/promtail.yml",
}
DEV_PROMETHEUS = BUNDLE.parent / "prometheus.yml"

# Credentials the stack cannot run safely without. Each must be required (`:?`) wherever compose
# reads it, and generated by `install.sh init`.
SECRETS = (
    "POSTGRES_PASSWORD",
    "EXAMLOPS_S3_ACCESS_KEY",
    "EXAMLOPS_S3_SECRET_KEY",
    "EXAMLOPS_S3_SERVING_ACCESS_KEY",
    "EXAMLOPS_S3_SERVING_SECRET_KEY",
    "CONTROL_PLANE_TOKEN",
    "DASHBOARD_VIEWER_PASSWORD",
    "DASHBOARD_ADMIN_PASSWORD",
    "DASHBOARD_JWT_SECRET",
    "DASHBOARD_SECRET_KEY",
)
# Values that have shipped as defaults in the development stack and must never reach an install.
WEAK_DEFAULTS = ("minioadmin", "changeme", ":-mlops}", ":-admin}", "GRAFANA_ADMIN_PASSWORD:-")
# Credentials read only by profile-gated services: generated like the others, read with no default.
GATED_SECRETS = ("GRAFANA_ADMIN_PASSWORD",)


def _compose() -> dict:
    return yaml.safe_load(COMPOSE.read_text())


def _services() -> dict[str, dict]:
    return _compose()["services"]


def _template_keys() -> dict[str, str]:
    keys = {}
    for line in TEMPLATE.read_text().splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            key, _, value = line.partition("=")
            keys[key.strip()] = value.strip()
    return keys


_VARIABLE = re.compile(r"\$\{([A-Z0-9_]+)(:[?-]|[?-]|)")


def _variables_in(text: str) -> list[tuple[str, str]]:
    """Every `${VAR<op>…}` compose interpolates from the host, as (name, operator).

    `$${…}` is escaped for the container's own shell and is not a host variable.
    """
    return _VARIABLE.findall(re.sub(r"\$\$\{[^}]*\}", "", text))


def _host_variables() -> list[tuple[str, str]]:
    return _variables_in(COMPOSE.read_text())


def _released_images() -> set[str]:
    workflow = yaml.safe_load(RELEASE.read_text())
    return {entry["name"] for entry in workflow["jobs"]["images"]["strategy"]["matrix"]["include"]}


def test_nothing_is_built_and_nothing_is_named_globally():
    for name, svc in _services().items():
        assert "build" not in svc, f"{name}: the bundle pulls released images, it never builds"
        assert "container_name" not in svc, (
            f"{name}: container_name makes two installs on one host collide; the project name "
            "(EXAMLOPS_PROJECT_NAME) already scopes every container"
        )
        assert "env_file" not in svc, (
            f"{name}: env_file hands every credential in .env to this container; pass only the "
            "variables it uses under environment:"
        )


def test_application_images_are_the_released_ones_at_the_bundle_version():
    released = _released_images()
    seen = set()
    for name, svc in _services().items():
        image = svc["image"]
        match = APP_IMAGE.match(image)
        if match:
            assert match["name"] in released, (
                f"{name}: {image} is not built by .github/workflows/release.yml "
                f"(publishes {sorted(released)}), so no release will ever contain it"
            )
            seen.add(match["name"])
        else:
            assert PINNED_UPSTREAM.match(image), (
                f"{name}: upstream image {image!r} must be pinned as tag@sha256:<digest>"
            )
    assert seen, "the bundle references no ExaMLOps image at all"


def test_nothing_is_mounted_from_outside_the_bundle():
    for name, svc in _services().items():
        for volume in svc.get("volumes", []):
            source = volume.split(":", 1)[0]
            if source.startswith(("$", ".", "/")):
                assert volume in (STATE_MOUNT, DOCKER_SOCKET_RO) or _SAFE_BIND.match(volume), (
                    f"{name}: bind mount {volume!r}; the bundle may mount its state dir, read-only "
                    "files it ships in ./monitoring, ./secrets/alertmanager read-only, and the "
                    "docker socket read-only — never the source tree"
                )
            assert ".." not in volume, f"{name}: {volume!r} reaches outside the bundle"
        # The raw socket is root on the host; only the scoped proxies may hold it.
        if DOCKER_SOCKET_RO in svc.get("volumes", []):
            assert name in SOCKET_PROXIES, f"{name} mounts the docker socket"


def test_every_service_on_the_data_root_resolves_the_same_pack():
    for name, svc in _services().items():
        if STATE_MOUNT not in svc.get("volumes", []):
            continue
        env = svc.get("environment", {})
        assert env.get("EXAMLOPS_DATA_DIR") == "/state", name
        assert env.get("EXAMLOPS_USECASE_DIR") == "/state/usecase", (
            f"{name}: without an explicit pack dir, an image with a baked pack would serve it "
            "while the dashboard shows none"
        )
        assert env.get("PLATFORM_DB") == "/state/platform.db", name


def test_the_data_root_is_initialised_before_anything_uses_it():
    services = _services()
    assert "instance init" in " ".join(services["instance-init"]["entrypoint"])
    for name, svc in services.items():
        if name == "instance-init" or STATE_MOUNT not in svc.get("volumes", []):
            continue
        if svc.get("profiles"):
            continue
        deps = svc.get("depends_on", {})
        chain = set(deps)
        for dep in deps:
            chain |= set(services[dep].get("depends_on", {}))
        assert "instance-init" in chain, f"{name} can start before the data root exists"


def test_the_data_root_is_writable_by_every_service():
    """Images do not share a uid (several run as 10001, some as root) and the data root is
    created by root.

    Without the hand-over, `/state/platform.db` is root-owned 0644 and a non-root service fails
    with "attempt to write a readonly database" — the agent's writes silently, the control plane
    by crash-looping at startup. So instance-init hands /state to the operator's uid/gid,
    group-writable, and every service that mounts it joins that group whatever uid its image
    uses today: an image that turns non-root later must not break the bundle.
    """
    services = _services()
    init = services["instance-init"]
    script = " ".join(init["entrypoint"])
    assert init.get("user") == "0:0", "only root can hand the data root over"
    assert 'chown -R "$${EXAMLOPS_STATE_UID}:$${EXAMLOPS_STATE_GID}" /state' in script
    assert "chmod -R g+rwX /state" in script and "chmod g+s" in script
    for name, svc in services.items():
        if name == "instance-init" or STATE_MOUNT not in svc.get("volumes", []):
            continue
        groups = svc.get("group_add") or []
        assert len(groups) == 1 and groups[0].startswith("${EXAMLOPS_STATE_GID"), (
            f"{name} mounts /state but does not join the data root's group"
        )


def test_postgres_is_healthy_only_when_it_accepts_tcp():
    """A socket probe passes during the image's first-start init server; dependents then fail."""
    test = " ".join(_services()["postgres"]["healthcheck"]["test"])
    assert "pg_isready -h 127.0.0.1" in test


def test_agent_memory_is_instance_data_the_backup_can_see():
    """The agent (uid 10001) cannot create files in a fresh root-owned named volume.

    Its memory stores therefore live in the group-writable data root — and the backup sidecar
    must read them from the same paths, or a bundle silently omits them.
    """
    services = _services()
    stores = ("AGENT_DB", "AGENT_MEMORY_DB", "AGENT_MEMORY_REVIEW_DB")
    agent_env = services["agent"]["environment"]
    backup_env = services["backup"]["environment"]
    for var in stores:
        assert agent_env[var].startswith("/state/agent/"), f"agent {var}={agent_env[var]}"
        assert backup_env[var] == agent_env[var], f"backup reads {var} from somewhere else"
    assert "mkdir -p /state/agent" in " ".join(services["instance-init"]["entrypoint"])


def test_the_object_store_is_replaceable():
    """The bundled MinIO is optional: its image gets no security fixes any more.

    It sits behind the `minio` profile (on by default through COMPOSE_PROFILES), every service
    reaches the store through EXAMLOPS_S3_ENDPOINT, and nothing that must run without MinIO
    depends on it unconditionally — or disabling the profile would make `up` refuse to start.
    """
    services = _services()
    assert _template_keys().get("COMPOSE_PROFILES") == "minio"
    for name in ("minio", "minio-init"):
        assert services[name].get("profiles") == ["minio"], f"{name} must be optional"
    assert "minio:9000" not in re.sub(r"(?m)^\s*#.*$", "", COMPOSE.read_text()), (
        "a service names the bundled MinIO directly; use ${EXAMLOPS_S3_ENDPOINT}"
    )
    for name, svc in services.items():
        if svc.get("profiles"):
            continue
        for dep, spec in (svc.get("depends_on") or {}).items():
            if services[dep].get("profiles"):
                assert spec.get("required") is False, (
                    f"{name} requires the optional service {dep}; mark it `required: false`"
                )


def test_bucket_names_are_settings():
    """Bucket names are global on public clouds, so none may be fixed in the compose file."""
    text = COMPOSE.read_text()
    for bucket in ("mlflow-artifacts", "examlops-projects", "dashboard-model-docs"):
        literal = re.findall(rf"(?<![-:]){re.escape(bucket)}", text)
        assert not literal, f"{bucket!r} is hard-coded outside a ${{VAR:-default}}"
    template = _template_keys()
    for key in (
        "EXAMLOPS_S3_ARTIFACT_BUCKET",
        "EXAMLOPS_PROJECTS_BUCKET",
        "DASHBOARD_MINIO_BUCKET",
    ):
        assert template.get(key), f"env.template must set {key}"


def _release_bundle_entries() -> set[str]:
    """Top-level names the release job copies into the bundle tarball."""
    workflow = yaml.safe_load(RELEASE.read_text())
    run = "\n".join(s.get("run", "") for s in workflow["jobs"]["github-release"]["steps"])
    listed = re.search(r"install/\{([^}]+)\}", run)
    assert listed, "the release no longer assembles the compose bundle"
    return set(listed.group(1).split(","))


def test_every_file_the_bundle_mounts_ships_with_the_release():
    entries = _release_bundle_entries()
    for name, svc in _services().items():
        for volume in svc.get("volumes", []):
            if volume.startswith("./") and not volume.startswith("./secrets/"):
                top = volume[2:].split("/", 1)[0]
                assert top in entries, f"{name} mounts {volume!r}; the release tarball omits {top}"
                assert (BUNDLE / volume[2:].split(":", 1)[0]).exists(), f"{name}: {volume!r}"


def test_secrets_can_never_ship_in_the_tarball():
    """The release dereferences ./monitoring into a public tarball; secrets live elsewhere.

    Alertmanager's receiver secrets sit in ./secrets (created by install.sh, gitignored, not in
    the release list), and everything reachable under ./monitoring — symlinks followed — must
    be a tracked file, so a bundle built from a working tree carries nothing a site wrote.
    """
    assert not any(
        e.startswith("secrets") or e in (".env", "state") for e in _release_bundle_entries()
    )
    assert "mkdir -p secrets/alertmanager" in INSTALL.read_text()
    tracked = set(
        subprocess.run(
            ["git", "ls-files", "platform/infra/docker-compose"],
            cwd=REPO,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    )
    reached = []
    for root, _dirs, files in os.walk(MONITORING, followlinks=True):
        for f in files:
            path = (Path(root) / f).resolve().relative_to(REPO).as_posix()
            reached.append(path)
            assert path in tracked or path in BUNDLE_OWN_MONITORING, (
                f"{path} would ship in the release tarball but is not tracked by git"
            )
    assert reached, "nothing under install/monitoring"


def test_shared_monitoring_config_is_linked_not_copied():
    """One source of truth: the shared configs are symlinks into the development stack's files.

    Grafana's provisioning is a directory symlink, deliberately: Docker resolves a mount *source*
    on the host, but symlinks *inside* a mounted directory resolve inside the container, where
    the development tree does not exist, so per-file links there leave Grafana empty when the
    bundle runs from a checkout. The release tarball dereferences them all (`cp -rL`).
    """
    shared = (
        "alert_rules.yml",
        "alertmanager.yml",
        "loki-config.yml",
        "tempo-config.yml",
        "grafana",
    )
    for name in shared:
        link = MONITORING / name
        assert link.is_symlink(), f"monitoring/{name} must link to the development stack's copy"
        assert link.resolve() == (BUNDLE.parent / name).resolve(), f"monitoring/{name}"


def test_bundle_prometheus_keeps_only_jobs_it_runs_and_copies_them_verbatim():
    """A job whose target is absent keeps `up == 0` firing TargetDown forever."""
    bundle = {
        j["job_name"]: j
        for j in yaml.safe_load((MONITORING / "prometheus.yml").read_text())["scrape_configs"]
    }
    dev = {j["job_name"]: j for j in yaml.safe_load(DEV_PROMETHEUS.read_text())["scrape_configs"]}
    services = set(_services())
    for job, spec in bundle.items():
        assert spec == dev.get(job), f"job {job!r} differs from ../prometheus.yml"
    for job, spec in dev.items():
        hosts = {t.split(":")[0] for sc in spec.get("static_configs", []) for t in sc["targets"]}
        runs_here = hosts and hosts <= services
        assert (job in bundle) == bool(runs_here or job == "fleet"), (
            f"job {job!r}: in the bundle={job in bundle}, but its targets {sorted(hosts)} "
            f"{'are' if runs_here else 'are not'} bundle services"
        )


def test_gated_credentials_are_generated_and_never_defaulted():
    template = _template_keys()
    for secret in GATED_SECRETS:
        assert template.get(secret, "").startswith("__GENERATE"), secret
        ops = {op for name, op in _host_variables() if name == secret}
        assert ops == {""}, f"{secret} must be read bare in profile-gated services; found {ops}"


def test_socket_proxies_grant_only_what_their_client_needs():
    """tecnativa's POST switch applies to every allowed section, so a proxy that may POST must
    not allow networks, images, exec or volumes; and each proxy lists every section explicitly."""
    services = _services()
    sections = {
        "CONTAINERS",
        "NETWORKS",
        "POST",
        "IMAGES",
        "VOLUMES",
        "EXEC",
        "INFO",
        "AUTH",
        "SECRETS",
        "SWARM",
        "SERVICES",
        "TASKS",
        "BUILD",
        "COMMIT",
        "CONFIGS",
        "DISTRIBUTION",
        "NODES",
        "PLUGINS",
        "SYSTEM",
    }
    for name in SOCKET_PROXIES:
        env = services[name]["environment"]
        assert sections <= set(env), f"{name} leaves {sorted(sections - set(env))} to defaults"
        if env["POST"] == "1":
            for risky in ("NETWORKS", "IMAGES", "EXEC", "VOLUMES", "BUILD", "SYSTEM"):
                assert env[risky] == "0", f"{name} may POST and allows {risky}"
    assert services["logs-proxy"]["environment"]["POST"] == "0"
    assert services["logs-proxy"].get("profiles") == ["monitoring"]


def test_mlflow_default_limit_clears_its_measured_footprint():
    """v0.54.0 shipped MLflow 3.16 under a 2g limit; resident at 2.1 GiB, it was OOM-killed on
    every start (kernel: memory cgroup out of memory). Keep the default at least 3g."""
    mlflow = _services()["mlflow"]
    limit = re.fullmatch(r"\$\{MLFLOW_MEM_LIMIT:-(\d+)g\}", mlflow["mem_limit"])
    assert limit and int(limit.group(1)) >= 3, mlflow["mem_limit"]
    assert "--workers ${MLFLOW_WORKERS:-2}" in mlflow["command"]


def test_ports_bind_where_the_operator_says():
    for name, svc in _services().items():
        for port in svc.get("ports", []):
            assert port.startswith(("${EXAMLOPS_BIND:-127.0.0.1}:", "127.0.0.1:")), (
                f"{name}: {port!r} publishes on every interface regardless of EXAMLOPS_BIND"
            )


def test_every_credential_is_required_and_generated():
    """Required (`:?`) in every core service; in a profile-gated one, read with no default.

    A profile-gated service may not use `:?` (compose interpolates before filtering by profile,
    so it would abort every command — test_compose_is_operable), but it must not fall back to a
    default either: the core services already refuse to start without the value.
    """
    template = _template_keys()
    core_ops: dict[str, set[str]] = {}
    gated_ops: dict[str, set[str]] = {}
    for svc in _services().values():
        ops = gated_ops if svc.get("profiles") else core_ops
        for name, op in _variables_in(yaml.safe_dump(svc, width=10_000)):
            ops.setdefault(name, set()).add(op)
    for secret in SECRETS:
        assert secret in core_ops, f"{secret} is never read by a core service"
        assert core_ops[secret] == {":?"}, (
            f"{secret} must be required (${{{secret}:?…}}) in every core service; "
            f"found {sorted(core_ops[secret])}"
        )
        assert gated_ops.get(secret, {""}) == {""}, (
            f"{secret} has a default in a profile-gated service: {sorted(gated_ops[secret])}"
        )
        assert template.get(secret, "").startswith("__GENERATE"), (
            f"env.template must let install.sh generate {secret}"
        )


def test_no_weak_default_survives():
    text = COMPOSE.read_text() + TEMPLATE.read_text()
    for weak in WEAK_DEFAULTS:
        assert weak not in text, f"{weak!r} appears in the install bundle"


def test_template_covers_every_required_variable_and_nothing_dead():
    template = _template_keys()
    used = {name for name, _ in _host_variables()}
    for name, op in _host_variables():
        if op in (":?", "?", ""):
            assert name in template, f"compose requires {name}, env.template does not set it"
    install = INSTALL.read_text()
    for key in template:
        if key.startswith("COMPOSE_"):
            continue  # read by docker compose itself (e.g. COMPOSE_PROFILES)
        assert key in used or key in install, f"env.template sets {key}, which nothing reads"


def _run_init(tmp_path: Path, *args: str) -> subprocess.CompletedProcess[str]:
    for f in (COMPOSE, TEMPLATE, INSTALL):
        shutil.copy2(f, tmp_path / f.name)
    return subprocess.run(
        ["sh", str(tmp_path / "install.sh"), "init", *args],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin"},
    )


def test_init_generates_every_secret_once_and_keeps_them_private(tmp_path):
    result = _run_init(tmp_path, "--version", "1.2.3")
    assert result.returncode == 0, result.stderr
    env_file = tmp_path / ".env"
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600
    assert (tmp_path / "state").is_dir()

    values = {}
    for line in env_file.read_text().splitlines():
        if line and not line.startswith("#"):
            key, _, value = line.partition("=")
            values[key] = value
    assert values["EXAMLOPS_VERSION"] == "1.2.3"
    assert values["EXAMLOPS_STATE_UID"] == str(os.getuid())
    assert values["EXAMLOPS_STATE_GID"] == str(os.getgid())
    assert not [k for k, v in values.items() if "__" in v], "a placeholder survived init"
    generated = [values[s] for s in SECRETS]
    assert len(set(generated)) == len(generated), "two credentials received the same value"
    assert all(len(v) >= 16 for v in generated)
    assert len(base64.urlsafe_b64decode(values["DASHBOARD_SECRET_KEY"])) == 32, "not a Fernet key"


def test_init_never_clobbers_an_existing_env(tmp_path):
    assert _run_init(tmp_path, "--version", "1.2.3").returncode == 0
    before = (tmp_path / ".env").read_text()
    again = _run_init(tmp_path, "--version", "1.2.3")
    assert again.returncode != 0 and "already exists" in again.stderr
    assert (tmp_path / ".env").read_text() == before


def test_init_refuses_without_a_version(tmp_path):
    result = _run_init(tmp_path)
    assert result.returncode != 0 and "no version" in result.stderr
    assert not (tmp_path / ".env").exists()


# A `.env` as `install.sh init` wrote it before the object store became replaceable (v0.52.0).
def _fake(tag: str) -> str:
    """A fake credential assembled at runtime. A literal `KEY=value` fixture line trips gitleaks'
    generic-api-key rule on the full-history gate (it did once: see .github/.gitleaksignore)."""
    return "-".join((tag, "old", "fixture"))


_FAKE = {
    "POSTGRES_PASSWORD": _fake("pg"),
    "MINIO_ROOT_USER": _fake("root"),
    "MINIO_ROOT_PASSWORD": _fake("minio"),
    "MINIO_SERVING_ACCESS_KEY": _fake("reader"),
    "MINIO_SERVING_SECRET_KEY": _fake("serving"),
}
_OLD_ENV = (
    "EXAMLOPS_VERSION=0.52.0\nEXAMLOPS_REGISTRY=ghcr.io/mskazemi\nPUBLIC_HOST=ops.example.org\n"
    + "".join(f"{name}={value}\n" for name, value in _FAKE.items())
)


def _env(path: Path) -> dict[str, str]:
    return dict(
        line.split("=", 1)
        for line in path.read_text().splitlines()
        if "=" in line and not line.startswith("#")
    )


def _run(tmp_path: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["sh", str(tmp_path / "install.sh"), *args],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin"},
    )


def test_upgrade_env_keeps_every_value_and_carries_renamed_ones(tmp_path):
    """An upgrade must never rotate a credential a volume already holds, nor drop an edit."""
    for f in (COMPOSE, TEMPLATE, INSTALL):
        shutil.copy2(f, tmp_path / f.name)
    (tmp_path / ".env").write_text(_OLD_ENV)
    (tmp_path / ".env").chmod(0o600)

    result = _run(tmp_path, "upgrade-env", "--version", "0.53.0")
    assert result.returncode == 0, result.stderr
    env = _env(tmp_path / ".env")
    assert env["EXAMLOPS_S3_ACCESS_KEY"] == _FAKE["MINIO_ROOT_USER"]  # MinIO's volume holds these
    assert env["EXAMLOPS_S3_SECRET_KEY"] == _FAKE["MINIO_ROOT_PASSWORD"]
    assert env["EXAMLOPS_S3_SERVING_ACCESS_KEY"] == _FAKE["MINIO_SERVING_ACCESS_KEY"]
    assert env["EXAMLOPS_S3_SERVING_SECRET_KEY"] == _FAKE["MINIO_SERVING_SECRET_KEY"]
    assert env["POSTGRES_PASSWORD"] == _FAKE["POSTGRES_PASSWORD"]
    assert env["PUBLIC_HOST"] == "ops.example.org"
    assert env["EXAMLOPS_VERSION"] == "0.53.0"
    assert set(_template_keys()) <= set(env), "a template setting is still missing"
    assert not [k for k, v in env.items() if v.startswith("__")], "a placeholder was copied"
    assert len(env["GRAFANA_ADMIN_PASSWORD"]) >= 16
    assert stat.S_IMODE((tmp_path / ".env").stat().st_mode) == 0o600

    before = (tmp_path / ".env").read_text()
    again = _run(tmp_path, "upgrade-env", "--version", "0.53.0")
    assert again.returncode == 0 and "No new settings" in again.stdout
    assert (tmp_path / ".env").read_text() == before


def test_every_renamed_setting_points_at_a_template_key():
    text = INSTALL.read_text()
    renamed = text[text.index('RENAMED="') + 9 : text.index('"', text.index('RENAMED="') + 9)]
    template = _template_keys()
    for pair in renamed.strip().splitlines():
        old, new = pair.split()
        assert new in template and old not in template, pair


@pytest.mark.skipif(shutil.which("docker") is None, reason="docker is not installed")
def test_compose_accepts_a_generated_env_and_rejects_a_missing_secret(tmp_path):
    assert _run_init(tmp_path, "--version", "1.2.3").returncode == 0
    ok = subprocess.run(
        ["docker", "compose", "config", "--quiet"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    if "is not a docker command" in ok.stderr:
        pytest.skip("docker compose v2 is not installed")
    assert ok.returncode == 0, ok.stderr

    env_file = tmp_path / ".env"
    env_file.write_text(
        re.sub(r"(?m)^POSTGRES_PASSWORD=.*$", "POSTGRES_PASSWORD=", env_file.read_text())
    )
    bad = subprocess.run(
        ["docker", "compose", "config", "--quiet"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    assert bad.returncode != 0 and "POSTGRES_PASSWORD" in bad.stderr
