"""ADR 0160 — `exa workbench export-pipeline`: tagged notebook → pipeline-DSL file.

Real extractor, real CLI runner, real `exa pipeline compile` validation path. Nothing is faked:
the generated file is loaded and compiled by the same code a hand-written pipeline file goes
through, and the "never executes the notebook" guarantee is proved with a sentinel a notebook
cell *would* write if anything ran it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
from typer.testing import CliRunner

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT / "platform" / "cli" / "src"))

from examlops.cli import surface  # noqa: E402
from examlops.cli.main import app  # noqa: E402
from examlops.pipeline_dsl import STEP_KINDS, IRError  # noqa: E402
from examlops.pipeline_dsl.notebook import (  # noqa: E402
    KNOWN_TAGS,
    STEP_TAGS,
    NotebookExportError,
    export_notebook,
    extract_notebook,
)

runner = CliRunner()

SENTINEL = "notebook_was_executed.txt"


def cell(source: str, tags: list[str] | None = None, kind: str = "code") -> dict:
    meta: dict = {}
    if tags is not None:
        meta["tags"] = tags
    return {
        "cell_type": kind,
        "source": source,
        "metadata": meta,
        "outputs": [],
        "execution_count": None,
    }


def notebook(tmp_path: Path, cells: list[dict], stem: str = "toy_notebook") -> Path:
    path = tmp_path / f"{stem}.ipynb"
    path.write_text(
        json.dumps({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}),
        encoding="utf-8",
    )
    return path


# The spec's §6 worked example, cell for cell, plus a cell that would write a sentinel file if
# anything ever executed the notebook.
PARAM_CELL = 'DS_NAME = "ToyDataset"\nCACHE_DIR = ".data_cache/toy"\nRMSE_PROD = 50.0\n'
DATASET_CELL = (
    "toy = {\n"
    '    "name": DS_NAME,\n'
    '    "backend": "zenodo",\n'
    '    "cache_dir": CACHE_DIR,\n'
    '    "input_features": ["x"],\n'
    '    "output_features": ["y"],\n'
    "}\n"
)
EDA_CELL = "# quick EDA\nimport matplotlib.pyplot as plt\nplt.hist(range(10))\n"
TRAIN_CELL = (
    "model = {\n"
    '    "datasets": ["toy"],\n'
    '    "config_class": "toy_config.ToyConfiguration",\n'
    '    "task_type": "regression",\n'
    '    "framework": "sklearn",\n'
    "}\n"
)
EVALUATE_CELL = 'metrics = {"model": "model"}\n'
PROMOTE_CELL = (
    "released = {\n"
    '    "metrics": "metrics",\n'
    '    "lifecycle": [\n'
    '        {"name": "Production", "metric": "rmse", "threshold": RMSE_PROD,\n'
    '         "direction": "lower_is_better"}\n'
    "    ],\n"
    "}\n"
)
SENTINEL_CELL = (
    "from pathlib import Path\n"
    f'Path("{SENTINEL}").write_text("the notebook was executed")\n'
    'raise SystemExit("and it even exited")\n'
)

EXPECTED_SOURCE = '''"""Generated by `exa workbench export-pipeline` from toy_notebook.ipynb. Edits here do not flow
back into the notebook — re-run export-pipeline to regenerate from a changed notebook instead."""

from examlops.sdk import dataset, evaluate, pipeline, promote, train


@pipeline(name="toy_notebook")
def toy_notebook():
    toy = dataset(
        "ToyDataset",
        backend="zenodo",
        cache_dir=".data_cache/toy",
        input_features=["x"],
        output_features=["y"],
    )
    model = train(
        toy,
        config_class="toy_config.ToyConfiguration",
        task_type="regression",
        framework="sklearn",
    )
    metrics = evaluate(model)
    released = promote(
        metrics,
        lifecycle=[
            {
                "name": "Production",
                "metric": "rmse",
                "threshold": 50.0,
                "direction": "lower_is_better",
            },
        ],
    )
'''


@pytest.fixture
def worked_example(tmp_path: Path) -> Path:
    return notebook(
        tmp_path,
        [
            cell("# Toy exploration", kind="markdown"),
            cell(PARAM_CELL, ["param"]),
            cell(DATASET_CELL, ["dataset"]),
            cell(EDA_CELL),
            cell(TRAIN_CELL, ["train"]),
            cell(EVALUATE_CELL, ["evaluate"]),
            cell(PROMOTE_CELL, ["promote"]),
            cell(SENTINEL_CELL, ["skip-export"]),
        ],
    )


@pytest.fixture
def env(tmp_path, monkeypatch):
    """A hermetic CLI environment: no shared platform.db, no inherited config, cwd in tmp."""
    monkeypatch.setenv("PLATFORM_DB", str(tmp_path / "platform.db"))
    monkeypatch.setenv("EXAMLOPS_CONFIG", str(tmp_path / "config.toml"))
    monkeypatch.setenv("EXAMLOPS_ACTOR", "tester")
    monkeypatch.chdir(tmp_path)
    return tmp_path


def _export(nb: Path, out: Path, *extra: str):
    return runner.invoke(app, ["workbench", "export-pipeline", str(nb), "--out", str(out), *extra])


# ── the tag vocabulary is the IR's own, not a parallel one ───────────────────────────────


def test_step_tags_are_exactly_the_lowerable_ir_step_kinds():
    """ADR 0160 decision 1: one vocabulary. A new lowerable kind must be a decision, not drift."""
    assert STEP_TAGS == tuple(k for k, spec in STEP_KINDS.items() if spec.lowerable)
    assert set(STEP_TAGS) == {"dataset", "train", "evaluate", "promote"}
    assert KNOWN_TAGS == {*STEP_TAGS, "param", "skip-export"}
    # hpo/custom_python are known to the IR but not lowerable, so they are not extractable.
    assert not {"hpo", "custom_python"} & KNOWN_TAGS


# ── the worked example, end to end ───────────────────────────────────────────────────────


def test_worked_example_emits_the_spec_source(worked_example):
    extraction = extract_notebook(worked_example)
    assert extraction.source == EXPECTED_SOURCE
    assert extraction.name == "toy_notebook"


def test_param_values_are_inlined_not_referenced(worked_example):
    """The generated file must stand alone — it may not depend on the notebook's names."""
    source = extract_notebook(worked_example).source
    for name in ("DS_NAME", "CACHE_DIR", "RMSE_PROD"):
        assert name not in source
    assert "threshold" in source and "50.0" in source


def test_generated_file_compiles_through_the_real_cli(env, worked_example):
    out = env / "toy_pipeline.py"
    res = _export(worked_example, out)
    assert res.exit_code == 0, res.output
    assert out.is_file()
    # The same artifact a hand-written pipeline file is: `exa pipeline compile` accepts it.
    ir = env / "toy.ir.json"
    compiled = runner.invoke(app, ["pipeline", "compile", str(out), "--out", str(ir)])
    assert compiled.exit_code == 0, compiled.output
    doc = json.loads(ir.read_text())
    assert doc["name"] == "toy_notebook"
    assert [n["kind"] for n in doc["nodes"]] == ["dataset", "train", "evaluate", "promote"]
    assert doc["content_hash"].startswith("sha256:")


def test_generated_ir_equals_a_hand_written_twin(env, worked_example):
    """Golden comparison that survives reformatting: the IR hash of a hand-written twin."""
    from examlops.pipeline_dsl.loader import load_pipeline_file

    out = env / "toy_pipeline.py"
    _, generated = export_notebook(worked_example, out)
    twin = env / "twin.py"
    twin.write_text(
        "from examlops.sdk import dataset, evaluate, pipeline, promote, train\n\n\n"
        '@pipeline(name="toy_notebook")\n'
        "def toy_notebook():\n"
        '    toy = dataset("ToyDataset", backend="zenodo", cache_dir=".data_cache/toy",\n'
        '                  input_features=["x"], output_features=["y"])\n'
        '    model = train(toy, config_class="toy_config.ToyConfiguration",\n'
        '                  task_type="regression", framework="sklearn")\n'
        "    metrics = evaluate(model)\n"
        "    promote(metrics, lifecycle=[{\n"
        '        "name": "Production", "metric": "rmse", "threshold": 50.0,\n'
        '        "direction": "lower_is_better"}])\n',
        encoding="utf-8",
    )
    pdef, _ = load_pipeline_file(str(twin))
    assert generated["content_hash"] == pdef.compile()["content_hash"]


def test_yaml_option_lowers_through_the_existing_lowering(env, worked_example):
    import yaml

    out, ypath = env / "toy_pipeline.py", env / "toy.yaml"
    res = _export(worked_example, out, "--yaml", str(ypath))
    assert res.exit_code == 0, res.output
    lowered = yaml.safe_load(ypath.read_text())
    assert lowered["name"] == "toy_notebook"
    assert [d["name"] for d in lowered["datasets"]] == ["ToyDataset"]


def test_name_option_overrides_the_notebook_stem(env, worked_example):
    out = env / "p.py"
    res = _export(worked_example, out, "--name", "ToyFlow")
    assert res.exit_code == 0, res.output
    assert '@pipeline(name="ToyFlow")' in out.read_text()


def test_out_defaults_to_the_notebook_stem(env, worked_example):
    res = runner.invoke(app, ["workbench", "export-pipeline", str(worked_example)])
    assert res.exit_code == 0, res.output
    assert (env / "toy_notebook_pipeline.py").is_file()


# ── nothing in the notebook is ever executed ─────────────────────────────────────────────


def test_notebook_code_is_never_executed(env, worked_example):
    """A `skip-export` cell writes a sentinel and raises SystemExit. Neither ever happens."""
    out = env / "toy_pipeline.py"
    res = _export(worked_example, out)
    assert res.exit_code == 0, res.output
    assert not (env / SENTINEL).exists()
    assert not list(env.rglob(SENTINEL))
    # Not even on the failing path: a notebook whose tagged cells are broken still runs nothing.
    broken = notebook(
        env,
        [cell(SENTINEL_CELL), cell('bad = {"name": open("x")}\n', ["dataset"])],
        stem="broken",
    )
    failed = _export(broken, env / "broken.py")
    assert failed.exit_code == 1
    assert not list(env.rglob(SENTINEL))


# ── dropping is never silent ─────────────────────────────────────────────────────────────


def test_untagged_code_cells_are_reported_as_dropped(env, worked_example):
    out = env / "toy_pipeline.py"
    res = _export(worked_example, out)
    assert res.exit_code == 0, res.output
    assert "Dropped 1 cell" in res.output
    assert "matplotlib" in res.output
    # Markdown narration is not a code cell and never warrants a warning.
    assert "Toy exploration" not in res.output


def test_dropped_cells_are_in_the_json_report(env, worked_example):
    out = env / "toy_pipeline.py"
    res = runner.invoke(
        app, ["--json", "workbench", "export-pipeline", str(worked_example), "--out", str(out)]
    )
    assert res.exit_code == 0, res.output
    payload = json.loads(res.stdout)
    assert payload["dropped"] == [
        {"index": 3, "preview": "# quick EDA / import matplotlib.pyplot as plt / plt.hist(ra…"}
    ]
    assert payload["steps"] == 4 and payload["name"] == "toy_notebook"
    assert payload["content_hash"].startswith("sha256:")
    assert payload["one_directional"] is True


def test_skip_export_is_dropped_without_a_warning(env):
    nb = notebook(
        env,
        [
            cell('ds = {"name": "D"}\n', ["dataset"]),
            cell("print('deliberately left out')\n", ["skip-export"]),
            cell("print('forgotten')\n"),
        ],
    )
    extraction = extract_notebook(nb)
    assert [d.index for d in extraction.dropped] == [2]
    assert "forgotten" in extraction.dropped[0].preview


def test_a_run_that_dropped_nothing_says_so(env):
    """Absence is reported, never inferred: "nothing dropped" is a statement, not silence."""
    nb = notebook(env, [cell('ds = {"name": "D"}\n', ["dataset"])], stem="only")
    res = _export(nb, env / "only.py")
    assert res.exit_code == 0, res.output
    assert "No cells dropped" in res.output
    assert extract_notebook(nb).dropped == []


def test_an_incomplete_export_is_the_irs_verdict_not_the_extractors(env):
    """A dataset with no train step still exports (spec §4.4) — the lowering is what refuses."""
    nb = notebook(env, [cell('ds = {"name": "D"}\n', ["dataset"])], stem="partial")
    assert _export(nb, env / "partial.py").exit_code == 0
    res = _export(nb, env / "partial.py", "--yaml", str(env / "partial.yaml"))
    assert res.exit_code == 1 and "always runs a 'train' step" in res.output


def test_an_unrecognised_tag_that_looks_like_a_typo_is_warned_about(env):
    nb = notebook(env, [cell('ds = {"name": "D"}\n', ["datasets"])], stem="typo")
    extraction = extract_notebook(nb)
    assert extraction.steps == []
    assert any(
        "'datasets' is not recognised" in w and "'dataset'" in w for w in extraction.warnings
    )
    assert [d.index for d in extraction.dropped] == [0]


# ── an invalid pipeline fails at export time, not at run time ────────────────────────────


def test_a_train_step_with_no_dataset_fails_export_with_the_compilers_message(env):
    nb = notebook(
        env,
        [
            cell('ds = {"name": "D"}\n', ["dataset"]),
            cell('m = {"config_class": "a.B", "task_type": "regression"}\n', ["train"]),
        ],
        stem="orphan",
    )
    out = env / "orphan.py"
    res = _export(nb, out)
    assert res.exit_code == 1
    assert "required input 'datasets' is not connected" in res.output
    # The file is still on disk so the author can see and fix what was generated (spec §3.7).
    assert out.is_file() and "def orphan" in out.read_text()


def test_an_unknown_param_fails_export_with_the_irs_own_wording(env):
    nb = notebook(
        env,
        [cell('ds = {"name": "D", "bogus": 1}\n', ["dataset"])],
        stem="bogus",
    )
    res = _export(nb, env / "bogus.py")
    assert res.exit_code == 1 and "unknown param" in res.output


def test_export_notebook_raises_the_ir_error_for_a_library_caller(env):
    """The compiler's own exception reaches a library caller unchanged — never re-worded."""
    nb = notebook(
        env,
        [cell('m = {"config_class": "a.B", "task_type": "regression"}\n', ["train"])],
        stem="lib",
    )
    with pytest.raises(IRError, match="required input 'datasets' is not connected"):
        export_notebook(nb, env / "lib.py")
    assert (env / "lib.py").is_file()


# ── hard failures: reject, do not guess (spec §4.2) ──────────────────────────────────────


@pytest.mark.parametrize(
    ("cells", "message"),
    [
        pytest.param(
            [cell('x = {"name": "D"}\n', ["dataset", "train"])],
            "several recognised tags",
            id="two-recognised-tags",
        ),
        pytest.param(
            [cell('x = {"name": open("f").read()}\n', ["dataset"])],
            "not extractable",
            id="a-call",
        ),
        pytest.param(
            [cell('x = {"name": f"{1}"}\n', ["dataset"])],
            "not extractable",
            id="an-f-string",
        ),
        pytest.param(
            [cell('x = {"name": n for n in []}\n', ["dataset"])],
            "dict literal",
            id="a-comprehension",
        ),
        pytest.param(
            [cell("import os\n", ["param"])],
            "must be 'NAME = <literal>'",
            id="an-import-in-a-param-cell",
        ),
        pytest.param(
            [cell('A = "x"\n', ["param"]), cell('A = "y"\n', ["param"])],
            "already declared by an earlier 'param' cell",
            id="a-duplicate-param",
        ),
        pytest.param(
            [cell('x = {"name": MISSING}\n', ["dataset"])],
            "is not declared by an earlier 'param' cell",
            id="an-unresolved-name",
        ),
        pytest.param(
            [cell('x = {"name": "D"}\ny = 1\n', ["dataset"])],
            "exactly one 'VAR = {...}' assignment",
            id="two-statements-in-a-step-cell",
        ),
        pytest.param(
            [cell('x = ["not", "a", "dict"]\n', ["dataset"])],
            "must be a dict literal",
            id="a-non-dict-step-cell",
        ),
        pytest.param(
            [
                cell('a = {"config_class": "a.B", "task_type": "r"}\n', ["train"]),
                cell('b = {"config_class": "a.B", "task_type": "r"}\n', ["train"]),
            ],
            "exactly one 'train' cell",
            id="two-train-cells",
        ),
        pytest.param(
            [
                cell('d = {"name": "D"}\n', ["dataset"]),
                cell(
                    'm = {"datasets": ["nope"], "config_class": "a.B", "task_type": "r"}\n',
                    ["train"],
                ),
            ],
            "not a tagged step cell's variable",
            id="an-unresolved-dataset-variable",
        ),
        pytest.param(
            [cell('e = {"split": "validation"}\n', ["evaluate"])],
            "needs 'model'",
            id="an-evaluate-cell-with-nothing-to-evaluate",
        ),
        pytest.param(
            [cell('train = {"config_class": "a.B", "task_type": "r"}\n', ["train"])],
            "name of the DSL helper",
            id="a-variable-shadowing-a-helper",
        ),
        pytest.param(
            [
                cell('d = {"name": "A"}\n', ["dataset"]),
                cell('d = {"name": "B"}\n', ["dataset"]),
            ],
            "already bound by an earlier tagged cell",
            id="a-duplicate-step-variable",
        ),
        pytest.param(
            [cell('x = {"name": "D"\n', ["dataset"])],
            "not valid Python",
            id="a-syntax-error",
        ),
        pytest.param(
            [cell('x = {"name": "D", "not an identifier": 1}\n', ["dataset"])],
            "is not a usable keyword",
            id="a-key-that-cannot-be-a-keyword",
        ),
    ],
)
def test_hard_failures_are_refused_with_the_offending_cell_named(env, cells, message):
    nb = notebook(env, cells, stem="bad")
    with pytest.raises(NotebookExportError) as exc:
        extract_notebook(nb)
    assert message in str(exc.value)
    res = _export(nb, env / "bad.py")
    assert res.exit_code == 1
    assert "Export failed" in res.output


def test_a_notebook_that_is_not_a_notebook_is_refused(env):
    junk = env / "not.ipynb"
    junk.write_text("{not json", encoding="utf-8")
    res = _export(junk, env / "x.py")
    assert res.exit_code == 1 and "Export failed" in res.output
    missing = _export(env / "nowhere.ipynb", env / "y.py")
    assert missing.exit_code == 1 and "not found" in missing.output


# ── CLI surface: tier and --out containment ──────────────────────────────────────────────


def _descriptor():
    return next(
        c for c in surface.build_catalog()["commands"] if c["path"] == "workbench export-pipeline"
    )


def test_the_command_is_tiered_admin():
    assert surface.TIERS["workbench export-pipeline"] == surface.ADMIN
    assert _descriptor()["tier"] == surface.ADMIN


def test_the_notebook_and_out_paths_are_contained_in_the_workspace(tmp_path):
    command = _descriptor()
    specs = {p["name"]: p for p in command["params"]}
    assert specs["notebook"].get("path") and specs["out"].get("path")
    assert specs["yaml_path"].get("path")
    inv = surface.build_argv(
        command, {"notebook": "nb/toy.ipynb", "out": "flows/toy.py"}, workspace=tmp_path
    )
    assert inv.tier == surface.ADMIN
    assert f"--out={tmp_path.resolve() / 'flows/toy.py'}" in inv.argv
    assert inv.argv[-1] == str(tmp_path.resolve() / "nb/toy.ipynb")
    assert sorted(inv.paths) == ["flows/toy.py", "nb/toy.ipynb"]


@pytest.mark.parametrize("escape", ["/etc/passwd", "../../outside.py", "~/secret.py"])
def test_a_path_outside_the_workspace_is_refused(tmp_path, escape):
    with pytest.raises(surface.SurfaceError):
        surface.build_argv(
            _descriptor(), {"notebook": "nb.ipynb", "out": escape}, workspace=tmp_path
        )


def test_the_help_says_it_is_one_directional():
    res = runner.invoke(app, ["workbench", "export-pipeline", "--help"])
    assert res.exit_code == 0
    text = " ".join(res.output.split())
    assert "One-directional" in text
    assert "does NOT flow back" in text
